## step to deploy hello world py app in cloud function
## yaml file format

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --source=.
  - --trigger-http
